"""check

Revision ID: 7073a500860c
Revises: 
Create Date: 2026-01-23 22:29:38.052684

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7073a500860c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
