"""initial

Revision ID: b29d7cb1fd09
Revises: 
Create Date: 2026-02-28 20:33:39.893584

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b29d7cb1fd09'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('availability_slots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('service_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('booked', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_id', 'date', name='uq_availability_service_date')
    )
    op.create_index(op.f('ix_availability_slots_date'), 'availability_slots', ['date'], unique=False)
    op.create_index(op.f('ix_availability_slots_service_id'), 'availability_slots', ['service_id'], unique=False)
    op.create_table('holds',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('pet_id', sa.Uuid(), nullable=False),
    sa.Column('service_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('quote_snapshot', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_holds_date'), 'holds', ['date'], unique=False)
    op.create_index(op.f('ix_holds_expires_at'), 'holds', ['expires_at'], unique=False)
    op.create_index(op.f('ix_holds_pet_id'), 'holds', ['pet_id'], unique=False)
    op.create_index(op.f('ix_holds_user_id'), 'holds', ['user_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('items_snapshot', sa.JSON(), nullable=False),
    sa.Column('total_snapshot', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('delivery_address_snapshot', sa.JSON(), nullable=True),
    sa.Column('ally_id', sa.Uuid(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hold_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_ally_id'), 'orders', ['ally_id'], unique=False)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_table('pets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('species', sa.String(length=20), nullable=False),
    sa.Column('breed', sa.String(length=100), nullable=True),
    sa.Column('sex', sa.String(length=10), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('sterilized', sa.Boolean(), nullable=True),
    sa.Column('size', sa.String(length=20), nullable=True),
    sa.Column('activity_level', sa.String(length=20), nullable=True),
    sa.Column('coat_type', sa.String(length=20), nullable=True),
    sa.Column('skin_sensitivity', sa.Boolean(), nullable=True),
    sa.Column('bath_behavior', sa.String(length=20), nullable=True),
    sa.Column('tolerates_drying', sa.Boolean(), nullable=True),
    sa.Column('tolerates_nail_clipping', sa.Boolean(), nullable=True),
    sa.Column('vaccines_up_to_date', sa.Boolean(), nullable=True),
    sa.Column('grooming_frequency', sa.String(length=100), nullable=True),
    sa.Column('receive_reminders', sa.Boolean(), nullable=True),
    sa.Column('antiparasitic', sa.Boolean(), nullable=True),
    sa.Column('antiparasitic_interval', sa.String(length=20), nullable=True),
    sa.Column('special_shampoo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pets_owner_id'), 'pets', ['owner_id'], unique=False)
    op.create_table('price_rules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('service_id', sa.Uuid(), nullable=False),
    sa.Column('species', sa.String(length=20), nullable=False),
    sa.Column('breed_category', sa.String(length=30), nullable=False),
    sa.Column('weight_min', sa.Float(), nullable=False),
    sa.Column('weight_max', sa.Float(), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_rules_service_id'), 'price_rules', ['service_id'], unique=False)
    op.create_table('services',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('species', sa.String(length=20), nullable=False),
    sa.Column('allowed_breeds', sa.JSON(), nullable=True),
    sa.Column('requires', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('sex', sa.String(length=10), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('dni', sa.String(length=30), nullable=True),
    sa.Column('address_district_id', sa.String(length=50), nullable=True),
    sa.Column('address_line', sa.String(length=255), nullable=True),
    sa.Column('address_lat', sa.Float(), nullable=True),
    sa.Column('address_lng', sa.Float(), nullable=True),
    sa.Column('profile_photo_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('order_assignments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('ally_id', sa.Uuid(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('assigned_by', sa.Uuid(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_assignments_ally_id'), 'order_assignments', ['ally_id'], unique=False)
    op.create_index(op.f('ix_order_assignments_order_id'), 'order_assignments', ['order_id'], unique=False)
    op.create_table('pet_weight_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pet_id', sa.Uuid(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pet_weight_entries_pet_id'), 'pet_weight_entries', ['pet_id'], unique=False)
    op.create_table('user_addresses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('district_id', sa.String(length=20), nullable=False),
    sa.Column('address_line', sa.String(length=255), nullable=False),
    sa.Column('reference', sa.Text(), nullable=True),
    sa.Column('building_number', sa.String(length=50), nullable=True),
    sa.Column('apartment_number', sa.String(length=50), nullable=True),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_addresses_user_default', 'user_addresses', ['user_id', 'is_default'], unique=False)
    op.create_index('ix_user_addresses_user_deleted', 'user_addresses', ['user_id', 'deleted_at'], unique=False)
    op.create_index('ix_user_addresses_user_id', 'user_addresses', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_addresses_user_id', table_name='user_addresses')
    op.drop_index('ix_user_addresses_user_deleted', table_name='user_addresses')
    op.drop_index('ix_user_addresses_user_default', table_name='user_addresses')
    op.drop_table('user_addresses')
    op.drop_index(op.f('ix_pet_weight_entries_pet_id'), table_name='pet_weight_entries')
    op.drop_table('pet_weight_entries')
    op.drop_index(op.f('ix_order_assignments_order_id'), table_name='order_assignments')
    op.drop_index(op.f('ix_order_assignments_ally_id'), table_name='order_assignments')
    op.drop_table('order_assignments')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('services')
    op.drop_index(op.f('ix_price_rules_service_id'), table_name='price_rules')
    op.drop_table('price_rules')
    op.drop_index(op.f('ix_pets_owner_id'), table_name='pets')
    op.drop_table('pets')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_ally_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_holds_user_id'), table_name='holds')
    op.drop_index(op.f('ix_holds_pet_id'), table_name='holds')
    op.drop_index(op.f('ix_holds_expires_at'), table_name='holds')
    op.drop_index(op.f('ix_holds_date'), table_name='holds')
    op.drop_table('holds')
    op.drop_index(op.f('ix_availability_slots_service_id'), table_name='availability_slots')
    op.drop_index(op.f('ix_availability_slots_date'), table_name='availability_slots')
    op.drop_table('availability_slots')
    # ### end Alembic commands ###
